[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
fs_permissions = [{ access = "read", path = "./"}]
ffi = true



[etherscan]
mainnet = { key = "${ETHERSCAN_MAINNET_KEY}" }
sepolia = { key = "${ETHERSCAN_MAINNET_KEY}" }

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[dependencies]
forge-std = { version = "1.9.2", url = "https://soldeer-revisions.s3.amazonaws.com/forge-std/1_9_2_06-08-2024_17:31:25_forge-std-1.9.2.zip" }
"@openzeppelin-contracts" = "4.9.6"
ethernaut = { version = "v1", git = "https://github.com/OpenZeppelin/ethernaut.git", rev = "06dc0b48d9113b06f1e114baf2d1c40ecb432d41" }
"@openzeppelin-contracts-3.4.2" = "3.4.2"

[fmt]
wrap_comments=true
line_length=80
multiline_func_header="all"

[soldeer]
remappings_generate = true
remappings_regenerate = false



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
